set -g mouse
set -g base-index 1
set -g escape-time 0
set-option -g status-interval 1
setw -g pane-base-index 1
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
set -s set-clipboard on
set -g allow-passthrough on
setw -g mode-keys vi
set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM

bind-key m \
  set-option -gF mouse "#{?mouse,off,on}" \;\
  display-message "#{?mouse,Mouse: ON,Mouse: OFF}"
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -i -selection clipboard"
bind P paste-buffer
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "xclip -i -selection clipboard"
set-window-option -g window-status-separator ''
set -g renumber-windows on

# cholorscheme
set -g status-style bg=default
set -g pane-border-style fg="#90b4fa"
set -g pane-active-border-style fg="#90b4fa"
set -g window-status-format "#[fg=#414869,bg=default]#[fg=#7aa2f7,bg=#414869]#I#[fg=#414869,bg=#292e42]#[fg=#7aa2f7,bg=#292e42] #W #[fg=#292e42,bg=default]"
set -g window-status-current-format "#[fg=#a1bff9,bg=default]#[fg=#080808,bg=#a1bff9]#I#[fg=#a1bff9,bg=#7aa2f7]#[fg=#080808,bg=#7aa2f7] #W #[fg=#7aa2f7,bg=default]"

if-shell "cat /etc/os-release | grep arch" 'OS_ICON='
if-shell "cat /etc/os-release | grep debian" 'OS_ICON='
if-shell '[ -n "$DEVCONTAINER" ]' "OS_ICON="

set -g status-right-length 100
set -g status-left-length 100
run 'tmux set -g status-left "#[fg=#7aa2f7,bg=#292e42] $OS_ICON #[fg=#292e42,bg=default]"'
set -g status-right "#[fg=#7aa2f7,bg=default] $USER #[fg=#292e42,bg=default]"
set -ag status-right "#[fg=#7aa2f7,bg=#292e42] 󱩛 $CUSTOM_HOST #[fg=#7aa2f7,bg=#292e42]"
set -agF status-right "#[fg=#080808,bg=#7aa2f7]  %H:%M:%S "

unbind C-b
unbind c
set-option -g prefix C-a
bind-key C-a send-prefix

# panes
bind '=' split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind-key c new-window -c "#{pane_current_path}"
bind-key h   select-pane -L
bind-key C-h select-pane -L
bind-key j   select-pane -D
bind-key C-j select-pane -D
bind-key k   select-pane -U
bind-key C-k select-pane -U
bind-key l   select-pane -R
bind-key C-l select-pane -R
bind-key -r "<" swap-pane -d -t -1
bind-key -r ">" swap-pane -d -t +1
bind-key -r H resize-pane -L 5
bind-key -r J resize-pane -D 5
bind-key -r K resize-pane -U 5
bind-key -r L resize-pane -R 5
