set -g mouse
set -g base-index 1
set -g escape-time 0
set-option -g status-interval 1
setw -g pane-base-index 1
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
set -s set-clipboard on
set -g allow-passthrough on
setw -g mode-keys vi
set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM

bind-key m \
  set-option -gF mouse "#{?mouse,off,on}" \;\
  display-message "#{?mouse,Mouse: ON,Mouse: OFF}"
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -i -selection clipboard"
bind P paste-buffer
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "xclip -i -selection clipboard"
set-window-option -g window-status-separator ''
set -g renumber-windows on

if-shell "cat /etc/os-release | grep arch" 'OS_ICON='
if-shell "cat /etc/os-release | grep debian" 'OS_ICON='
if-shell "cat /etc/os-release | grep nixos" 'OS_ICON=󱄅'
if-shell '[ -n "$DEVCONTAINER" ]' "OS_ICON="

# ==========================================
# THEME VARIABLES
# ==========================================
set -g @pane_border "#80a0ff"  # Moonfly Blue (normal)
set -g @bg_main "#080808"      # Moonfly Background (Dark Charcoal/Black)
set -g @bg_alt "#323437"       # Moonfly Black (normal) - used for secondary backgrounds
set -g @accent_main "#80a0ff"  # Moonfly Blue (normal)
set -g @accent_alt "#b2ceee"   # Moonfly Selection Blue (lighter)
set -g @text_dark "#080808"    # Contrast color for text on active blocks

# ==========================================
# COLORSCHEME
# ==========================================
set -g status-style bg=default
set -g pane-border-style fg="#{@pane_border}"
set -g pane-active-border-style fg="#{@pane_border}"

set -g window-status-format "#[fg=#{@bg_alt},bg=default]#[fg=#{@accent_main},bg=#{@bg_alt}]#I#[fg=#{@bg_alt},bg=#{@bg_main}]#[fg=#{@accent_main},bg=#{@bg_main}] #W #[fg=#{@bg_main},bg=default]"
set -g window-status-current-format "#[fg=#{@accent_alt},bg=default]#[fg=#{@text_dark},bg=#{@accent_alt}]#I#[fg=#{@accent_alt},bg=#{@accent_main}]#[fg=#{@text_dark},bg=#{@accent_main}] #W #[fg=#{@accent_main},bg=default]"

set -g status-right-length 100
set -g status-left-length 100
run 'tmux set -g status-left "#[fg=#{@accent_main},bg=#{@bg_main}] $OS_ICON #[fg=#{@bg_main},bg=default]"'
set -g status-right "#[fg=#{@accent_main},bg=default] $USER #[fg=#{@bg_main},bg=default]"
set -ag status-right "#[fg=#{@accent_main},bg=#{@bg_main}] 󱩛 $CUSTOM_HOST #[fg=#{@accent_main},bg=#{@bg_main}]"
set -agF status-right "#[fg=#{@text_dark},bg=#{@accent_main}]  %H:%M:%S "

# ==========================================
# KEYBINDINGS
# ==========================================
unbind C-b
unbind c
set-option -g prefix C-a
bind-key C-a send-prefix

# panes
bind '=' split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind-key c new-window -c "#{pane_current_path}"
bind-key h   select-pane -L
bind-key C-h select-pane -L
bind-key j   select-pane -D
bind-key C-j select-pane -D
bind-key k   select-pane -U
bind-key C-k select-pane -U
bind-key l   select-pane -R
bind-key C-l select-pane -R
bind-key -r "<" swap-pane -d -t -1
bind-key -r ">" swap-pane -d -t +1
bind-key -r H resize-pane -L 5
bind-key -r J resize-pane -D 5
bind-key -r K resize-pane -U 5
bind-key -r L resize-pane -R 5
