export PATH=$PATH:$HOME/.local/bin:/opt/nvim-linux-x86_64/bin
export XDG_CONFIG_HOME=$HOME/.config
export CUSTOM_HOST=${DEVCONTAINER_NAME:-${HOST}}
bind 'set completion-ignore-case on'

alias vi="nvim"
alias tmux="tmux new-session -A -s $USER"

alias gb="git branch"
alias gca="git add -A && git commit -m"
alias gc="git commit -m"
alias gs="git status"
alias gd="git diff"
alias gp="git push"
alias gu="git pull"
alias gl="git log"

alias sqlite=sqlite3

#------------- Autogenerated config
# If not running interactively, don't do anything
case $- in
*i*) ;;
*) return ;;
esac

HISTCONTROL=ignoreboth
shopt -s histappend
HISTSIZE=1000
HISTFILESIZE=2000
shopt -s checkwinsize

if [ -f ~/.bash_aliases ]; then
  . ~/.bash_aliases
fi

#enable completion
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi
#------------- Autogenerated config

#load oh-my-posh
if command -v oh-my-posh &>/dev/null; then
  eval "$(oh-my-posh init bash --config ~/dotfiles/.config/oh-my-posh/custom.omp.toml)"
fi

#load nvm completion
if [ -d "$HOME/.nvm/" ]; then
  export NVM_DIR="$HOME/.nvm"
  [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"                   # This loads nvm
  [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion" # This loads nvm bash_completion
fi
