#!/usr/bin/env bash

IN=$(devcontainer list)
echo $power

options=""
IFS=' ' read -ra ADDR <<< "$IN"
for i in "${ADDR[@]}"; do
  options+="${i%%|*}\n"
done
chosen=$(echo -e "$options" | walker --dmenu --placeholder "Connect to Devcontainer" | xargs)
container="${chosen%%.*}"


if [[ -n "$container" ]]; then
  ghostty -e devcontainer connect $container
fi

