theme="tokyo-night"

[[plugins]]
name = "clipboard"
placeholder = "Clipboard"

force_keyboard_focus = true
selection_wrap = true
hide_action_hints = true

[placeholders]
"default" = { input = " Search...", list = "No Results" }

[keybinds]
quick_activate = []
next = ["Down", "ctrl j"]
previous = ["Up", "ctrl k"]

[columns]
symbols = 1

[providers]
max_results = 256
default = [
  "desktopapplications",
  "websearch",
]

[[providers.prefixes]]
prefix = "/"
provider = "providerlist"

[[providers.prefixes]]
prefix = "."
provider = "files"

[[providers.prefixes]]
prefix = ":"
provider = "symbols"

[[providers.prefixes]]
prefix = "="
provider = "calc"

[[providers.prefixes]]
prefix = "@"
provider = "websearch"

[[providers.prefixes]]
prefix = "$"
provider = "clipboard"

# [style]
# layout = "center"
#
# [effects]
# blur = true

