theme="tokyo-night"
force_keyboard_focus = true
selection_wrap = true
hide_action_hints = true

[[plugins]]
name = "clipboard"
placeholder = "Clipboard"

[[plugins]]
name = "notifications"
placeholder = "Notifications"
show_items_anyway = true
terminal = false
command = '/home/raul/.local/bin/scripts/walker-mako'

[plugins.switcher]
maintain_state = false
command = "makoctl dismiss --all" # Example: clear all on selection


[placeholders]
"default" = { input = " Search...", list = "No Results" }

[keybinds]
quick_activate = []
next = ["Down", "ctrl j"]
previous = ["Up", "ctrl k"]

[columns]
symbols = 1

[providers]
max_results = 256
default = [
  "desktopapplications",
  "websearch",
]

[[providers.prefixes]]
prefix = "/"
provider = "providerlist"

[[providers.prefixes]]
prefix = "."
provider = "files"

[[providers.prefixes]]
prefix = ":"
provider = "symbols"

[[providers.prefixes]]
prefix = "="
provider = "calc"

[[providers.prefixes]]
prefix = "@"
provider = "websearch"

[[providers.prefixes]]
prefix = "$"
provider = "clipboard"

# [style]
# layout = "center"
#
# [effects]
# blur = true

