#!/bin/bash

if [ "$1" == "up" ]; then
    ddcutil --sleep-multiplier 0.1 --noverify --skip-ddc-checks --bus 7 setvcp 10 + 10
else
    ddcutil --sleep-multiplier 0.1 --noverify --skip-ddc-checks --bus 7 setvcp 10 - 10
fi
# NEW_VAL=$(ddcutil getvcp 10 -t | cut -d ' ' -f 4)
# NEW_VAL=$(echo "$NEW_VAL / 100" | bc -l)
# swayosd-client --custom-progress $NEW_VAL --custom-icon "display-brightness"
