-- vim.pack.add {"gh:stevearc/conform.nvim"}
-- require("conform").setup({
--   formatters_by_ft = {
--     lua = { "stylua" },
--     javascript = { "prettierd", "prettier", stop_after_first = true },
--     typescript = { "prettierd", "prettier", stop_after_first = true },
--   },
-- })
--
-- vim.api.nvim_create_autocmd("BufWritePre", {
--   pattern = "*",
--   callback = function(args)
--     require("conform").format({ bufnr = args.buf })
--   end,
-- })
print('conform disabled')
