[font]
size = 14

[font.normal]
family = "Hack Nerd Font"
style = "Medium"

[window]
opacity = 0.9
decorations="None"

[general]
live_config_reload = true
import=["~/dotfiles/.config/alacritty/moonfly.toml"]

[env]
TERM="xterm-256color"

[keyboard]
bindings=[{ "key"="Q", "mods"="Control", "action"="Quit" }]

