[font]
size = 14

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[window]
opacity = 0.9
decorations="None"

[general]
live_config_reload = true
import=["~/dotfiles/.config/alacritty/moonfly.toml"]

[env]
TERM="xterm-256color"
