"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
console_title_template = "{{if .Env.DEVCONTAINER }} {{end}}{{regexReplaceAll \"(.)(/.*/)\" .PWD \"${1}/../\"}}"
version = 3

[transient_prompt]
  foreground = "#82aaff"
  style = "plain"
  type = "text"
    template = " "

[[blocks]]
alignment = "left"
type = "prompt"

  [[blocks.segments]]
  type = "os"
  style = "diamond"
  background = "#82aaff"
  foreground = "#060606"
  template = " {{if .Env.DEVCONTAINER}}{{else}}{{.Icon}}{{end}} "

    [blocks.segments.properties]
    macos = "mac"

  [[blocks.segments]]
  background = "#82aaff"
  foreground = "#060606"
  powerline_symbol = ""
  style = "powerline"
  template = "   {{ .Path }}"
  type = "path"

    [blocks.segments.properties]
    folder_separator_icon = "/"
    style = "agnoster_short"

  [[blocks.segments]]
  background = "#3b4261"
  foreground = "#82aaff"
  powerline_symbol = ""
  style = "powerline"
  type = "git"
  template = "({{ .UpstreamIcon }} {{ .HEAD }}) {{if .BranchStatus }}{{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}"

    [blocks.segments.properties]
    fetch_upstream_icon = true
    fetch_status = true
    branch_icon = ""

[[blocks]]
alignment = "right"
overflow = "hide"
type = "prompt"

  [[blocks.segments]]
  background = "#3b4261"
  foreground = "#82aaff"
  powerline_symbol = ""
  style = "powerline"
  template = " {{ .FormattedMs }}s "
  type = "executiontime"

    [blocks.segments.properties]
    style = "dallas"
    threshold = 0

  [[blocks.segments]]
  powerline_symbol = ""
  trailing_powerline_symbol = ""
  background = "#82aaff"
  foreground = "#060606"
  style = "powerline"
  template = " {{ .CurrentDate | date .Format }} "
  type = "time"

    [blocks.segments.properties]
    time_format = "15:04:05"

  [[blocks.segments]]
  background = "#82aaff"
  foreground = "#060606"
  style = "diamond"
  type = "status"
  background_templates = [ "{{ if .Error }}#e91e63{{else}}#36c692{{ end }}" ]
  template = "  "

    [blocks.segments.properties]
    always_enabled = true

[[blocks]]
alignment = "left"
newline = true
type = "prompt"

  [[blocks.segments]]
  foreground = "#f38ba8"
  style = "plain"
  template = "  "
  type = "root"

  [[blocks.segments]]
    type = "text"
    style = "plain"
    foreground = "#82aaff"
    template = " "

