"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
# console_title_template = "{{regexReplaceAll \"(.)(/.*/)\" .PWD \"${1}/../\"}}"
# console_title_template = " {{.PWD}}"
console_title_template = " {{last (regexSplit \"/\" .PWD -1)}}"
version = 3
# moonfly
[palette]
accent = "#80a0ff"
secondary = "#303030"
error = "#e91e63"
success = "#36c692"
background = "#080808"
root = "#f38ba8"

# # tokyonight
# [palette]
# accent = "#82aaff"
# secondary = "#3b4261"
# error = "#f7768e"
# success = "#9ece6a"
# background = "#1a1b26"
# root = "#f38ba8"

[transient_prompt]
  foreground = "p:accent"
  style = "plain"
  type = "text"
    template = "󰇁 "

[[blocks]]
alignment = "left"
type = "prompt"

  [[blocks.segments]]
  type = "os"
  style = "diamond"
  background = "p:secondary"
  foreground = "p:accent"
  template = " {{if .Env.DEVCONTAINER}}{{else}}{{.Icon}}{{end}} "

    [blocks.segments.properties]
    macos = ""

  [[blocks.segments]]
  background = "p:accent"
  foreground = "p:background"
  powerline_symbol = ""
  style = "powerline"
  template = " {{ .Path }}"
  type = "path"

    [blocks.segments.properties]
    display_root=true
    style = "letter"

  [[blocks.segments]]
  background = "p:secondary"
  foreground = "p:accent"
  powerline_symbol = ""
  style = "powerline"
  type = "git"
  template = " ({{ .UpstreamIcon }} {{ .HEAD }}) {{if .BranchStatus }}{{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }}"

    [blocks.segments.properties]
    fetch_upstream_icon = true
    fetch_status = true
    branch_icon = ""

[[blocks]]
alignment = "right"
overflow = "hide"
type = "prompt"

  [[blocks.segments]]
  background = "p:secondary"
  foreground = "p:accent"
  leading_diamond = ""
  style = "diamond"
  template = "󰔛 {{ .FormattedMs }} "
  type = "executiontime"

    [blocks.segments.properties]
    threshold = 0

  [[blocks.segments]]
  background = "p:accent"
  foreground = "p:background"
  leading_diamond = ""
  style = "diamond"
  type = "status"
  background_templates = [ "{{ if .Error }}p:error{{else}}p:success{{ end }}" ]
  template =  "{{ if .Error }} {{else}} {{ end }}"

    [blocks.segments.properties]
    always_enabled = true

[[blocks]]
alignment = "left"
newline = true
type = "prompt"

  [[blocks.segments]]
  foreground = "p:root"
  style = "plain"
  template = "  "
  type = "root"

  [[blocks.segments]]
    type = "text"
    style = "plain"
    foreground = "p:accent"
    template = "󰇁 "

